Add array support to run
JaimeGensler/thyseus pull request #14
Opened 2023-05-14 04:59 UTC by kayhhh

untested

2023-05-14 16:49 UTC, JaimeGensler requested changes
Looks great overall - thanks so much for taking care of this! Left a couple style nits to keep things inline with the rest of the codebase.
Lack of test setup here is my bad once again, I'll get to it - if you could leave a simple "TODO: Tests" comment at the bottom of this file that would be super helpful for me 😄 

I know this expands the scope here a bit, but if you're willing (& agree with my thinking), it would probably be good if `addSystems()` could accept System/SystemConfig arrays without spreading, too. If you'd rather be done here, I'll handle that myself 🙂 

Thanks again!

2023-05-14 16:49 UTC, JaimeGensler commented on src/schedule/run.ts
> +			if (Array.isArray(system)) this.dependents.push(...system);
Stylistic nit: Would prefer not using single-line if/else here (and elsewhere), braces/blocks help me parse control flow more quickly and is more consistent with the rest of the codebase 🙂

2023-05-14 16:49 UTC, JaimeGensler commented on src/schedule/run.ts
> +		i === 0
Style nit: would prefer to remove this nested ternary. Could just move this first case (`i === 0`) to an `if` and then use a (no longer nested) ternary in the return

2023-05-14 16:49 UTC, JaimeGensler commented on src/schedule/run.ts
> +	): (System | System[] | SystemConfig | SystemConfig[])[];
I think we'll end up using this `(System | System[] | SystemConfig | SystemConfig[])[]` type a lot - we could extract it to its own type & export here (e.g. `SystemList`, or whatever sounds best), for use elsewhere, too

2023-05-16 05:36 UTC, kayhhh commented
I can add `addSystems()` array support, probably good to have all system APIs like this to support the same syntax of accepting both plain systems and arrays.

2023-05-16 05:37 UTC, kayhhh commented
Will assume this includes `addSystemsToSchedule()`

2023-05-16 05:59 UTC, kayhhh commented
Hm, so I did find an issue with the `run` changes I added. Using arrays like `run([systemA]).last()` throws an error, because run is returning `SystemConfigs[]`, not a singular config. I can just remove array support here unless you can think of a way to resolve it. `run.chain` should still work fine.

Also sidenote, is there a reason for `dist` to be committed? I typically run build to catch errors like this (and it is how I found it now), but its a bit annoying to have to remove my files after the build so they aren't committed.

2023-05-17 01:28 UTC, JaimeGensler commented
>  I can just remove array support here unless you can think of a way to resolve it

Wondering if it's reasonable for `SystemConfig` itself to accept multiple systems, so run could pass the array directly to `SystemConfig` and all systems can be configured together. There may be some issues with this I haven't thought of, but it's a potential solution.

> Also sidenote, is there a reason for dist to be committed?

Originally I thought it'd make it easier to keep an eye on build output for anything problematic/odd, but I've also felt lately it's more tedious than helpful. Feel free to add it to the .gitignore here & delete the folder in this PR, or I'll do it in a follow-up.

2023-05-18 15:10 UTC, JaimeGensler commented
That makes sense! Expanding support also brings up a lot of questions around things like permitted depth of nesting, which requires a bit more thought. Going to re-review a little later and should be able to get this merged, thanks! 🙌

2023-05-19 11:49 UTC, kayhhh commented
Sounds good. I removed array support from `run(...)` since it was causing issues, should be working for `run.chain`, `.after`, and `.before`.

2023-05-20 16:05 UTC, JaimeGensler approved these changes
Looks great! Thanks for the revert on `run()`, I think it's something that'll be good to do eventually but there's definitely some questions that need answering first.

2023-05-20 16:07 UTC, merged